
INSERT INTO TRAITS(TRAIT, POINTS) VALUES ('EXTROVERT',0);
INSERT INTO TRAITS(TRAIT, POINTS) VALUES ('LAGSPELARE',0);
INSERT INTO TRAITS(TRAIT, POINTS) VALUES ('NISCHAD',0);
INSERT INTO TRAITS(TRAIT, POINTS) VALUES ('NOGGRANNHET',0);
INSERT INTO TRAITS(TRAIT, POINTS) VALUES ('RÄTTFRAM',0);


--INSERT INTO YRKE(YRKESTITEL) VALUES ('LÄRARE');
--INSERT INTO YRKE(YRKESTITEL) VALUES ('PROGRAMMERARE');
--INSERT INTO YRKE(YRKESTITEL) VALUES ('BREVBÄRARE');
--INSERT INTO YRKE(YRKESTITEL) VALUES ('POLIS');
--INSERT INTO YRKE(YRKESTITEL) VALUES ('FASTIGHETSMÄKLARE');


INSERT INTO QUESTIONS(QUESTION, ANSWER, TRAITS_TRAITSID) VALUES ('FÅR DU ENERGI NÄR DU UMGÅS MED ANDRA MÄNNISKOR?',0,1);
INSERT INTO QUESTIONS(QUESTION, ANSWER, TRAITS_TRAITSID) VALUES ('FÖREDRAR DU ATT JOBBA I GRUPP FRAMFÖR ATT JOBBA SJÄLVSTÄNDINGT?',0,2);
INSERT INTO QUESTIONS(QUESTION, ANSWER, TRAITS_TRAITSID) VALUES ('FÖREDRAR DU ATT ANVÄNDA EN BEPRÖVAD LÖSNING FRAMFÖR ATT TESTA NYA LÖSNINGAR?',0,3);
INSERT INTO QUESTIONS(QUESTION, ANSWER, TRAITS_TRAITSID) VALUES ('FÖREDRAR DU ATT HA EN PLAN FRAMFÖR ATT TA DET SOM DET KOMMER?',0,4);
INSERT INTO QUESTIONS(QUESTION, ANSWER, TRAITS_TRAITSID) VALUES ('OM DU INTE HÅLLER MED DIN KOLLEGA, SÄGER DU IFRÅN DÅ?',0,5);
